### ISSUE TITLE
"unable to find matching page for URL: {url}"

### ISSUE THREAD

**Issue by stormmurdoc** [hunyadi/md2conf#18]
Since version 0.19 I experience a problem when rendering email addresses. The following error message appears: 

`2023-10-19 06:33:28,517 - INFO - _synchronize_page [87] - Synchronizing page: README.md
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/md2conf/__main__.py", line 85, in <module>
    Application(api, ConfluenceDocumentOptions(args.generated_by)).synchronize(
  File "/usr/local/lib/python3.12/site-packages/md2conf/application.py", line 34, in synchronize
    self.synchronize_page(path)
  File "/usr/local/lib/python3.12/site-packages/md2conf/application.py", line 41, in synchronize_page
    self._synchronize_page(page_path, dict())
  File "/usr/local/lib/python3.12/site-packages/md2conf/application.py", line 88, in _synchronize_page
    document = ConfluenceDocument(page_path, self.options, page_metadata)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/md2conf/converter.py", line 5[31](https://gitlab.*****), in __init__
    converter.visit(self.root)
  File "/usr/local/lib/python3.12/site-packages/md2conf/converter.py", line 198, in visit
    self.visit(source)
  File "/usr/local/lib/python3.12/site-packages/md2conf/converter.py", line 198, in visit
    self.visit(source)
  File "/usr/local/lib/python3.12/site-packages/md2conf/converter.py", line 194, in visit
    target = self.transform(source)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/md2conf/converter.py", line [42](https://gitlab*****)0, in transform
    return self._transform_link(child)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/md2conf/converter.py", line 260, in _transform_link
    raise DocumentError(f"unable to find matching page for URL: {url}")
md2conf.converter.DocumentError: unable to find matching page for URL: mailto:test@test.com`

**Comment by hunyadi** [comment]
I have pushed changes to the branch `master` to improve the robustness of identifying absolute and relative URLs. I have also added an example of an e-mail address to the sample files. Can you confirm you are no longer getting the error message with the latest state on the branch `master`?

**Comment by amorphina** [comment]
Hey @hunyadi, I have tested the changes from master and the email handling seems to be working properly.
Can you please upgrade the PIP version as well.
Thanks!
