### ISSUE TITLE
400 client error for a child attachment

### ISSUE THREAD

**Issue by theophile-scrive** [hunyadi/md2conf#2]
The file I'm trying to publish has an image linked in it. 
The Confluence API returns a 400 when I use md2conf.

Unfortunately the API is not very talkative about the reason of the error, and perhaps the image is a red herring and the real reson is elsewhere.

Here is the stacktrace:

```
2023-05-30 17:46:45,724 - INFO - upload_attachment [221] - Uploading attachment: ./multi-sign-graph.png
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/md2conf/__main__.py", line 59, in <module>
    synchronize_page(api, args.mdfile)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/md2conf/application.py", line 28, in synchronize_page
    update_document(api, document, base_path)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/md2conf/application.py", line 11, in update_document
    api.upload_attachment(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/md2conf/api.py", line 228, in upload_attachment
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/requests/models.py", line 10[21](https://github.com/[…]), in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://[…]/child/attachment
```

**Comment by hunyadi** [comment]
I have added more detailed error logging and reporting in the latest commit to `master`, which can help pinpoint the root cause. This will be included in the next release of [markdown-to-confluence](https://pypi.org/project/markdown-to-confluence/) published to PyPI.
