### ISSUE TITLE
How is the `-r` option supposed to be used?

### ISSUE THREAD

**Issue by rj93-finseta** [hunyadi/md2conf#59]
I would like to create some markdown files freely in git, and have a CI pipeline automatically publish them to confluence with automatic creation of new pages.

I can see the following option in the docs:

```
-r ROOT_PAGE          Root Confluence page to create new pages. If omitted, will raise exception when creating new pages.
```

However when I run:

```
md2conf -d example.atlassian.net \
  -u example@finseta.com\
  -a example \
  -s Example \
  -r 1085308929 \
  test.md
```

It throws:

```
2024-09-27 16:22:17,513 - INFO - _synchronize_page [80] - Synchronizing page: test.md
Traceback (most recent call last):
  File "/Users/rich/.local/bin/md2conf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/rich/.local/pipx/venvs/markdown-to-confluence/lib/python3.12/site-packages/md2conf/__main__.py", line 154, in main
    ).synchronize(args.mdpath)
      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rich/.local/pipx/venvs/markdown-to-confluence/lib/python3.12/site-packages/md2conf/application.py", line 36, in synchronize
    self.synchronize_page(path)
  File "/Users/rich/.local/pipx/venvs/markdown-to-confluence/lib/python3.12/site-packages/md2conf/application.py", line 43, in synchronize_page
    self._synchronize_page(page_path, {})
  File "/Users/rich/.local/pipx/venvs/markdown-to-confluence/lib/python3.12/site-packages/md2conf/application.py", line 81, in _synchronize_page
    document = ConfluenceDocument(page_path, self.options, page_metadata)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rich/.local/pipx/venvs/markdown-to-confluence/lib/python3.12/site-packages/md2conf/converter.py", line 790, in __init__
    raise ValueError("missing Confluence page ID")
ValueError: missing Confluence page ID
```

**Comment by hemstreet** [comment]
I think i'm doing exactly what you are talking about wanting to do. I synchronize entire folders rather than individual files, but should operate in the same way. If you want to sync one file, you could always make a docs repo and just change the path that it looks in. 

I.E

You can do this in two ways.

1) If you want to publish to a Space's root page. Go to the overview page, which the url will look something like `https://xxx.atlassian.net/wiki/spaces/RJ93/overview`, if you click edit the url will change to `https://xxx.atlassian.net/wiki/spaces/RJ93/pages/edit-v2/123456`. Where `123456` is your root page id.

2) You can navigate to an existing confluence, and grab the id out of the url which will look something like `https://xxx.atlassian.net/wiki/spaces/RJ93/pages/4321/Foo`, where `4321` is the root id.

Now that you have the root id, you can run the md2conf script like this `python3 -m md2conf -r {YOUR_ROOT_ID} ./`, or change your docs folder to  `python3 -m md2conf -r {YOUR_ROOT_ID} ./docs`.


Now the caveat is, at the time of writing this, the folder structure on the dev branch is more straightforward, so pick and choose on how you use this.

**Comment by hunyadi** [comment]
I have added a new section to the documentation on how to [publish a directory](https://github.com/hunyadi/md2conf?tab=readme-ov-file#publishing-a-directory) and how *md2conf* recursively scans the directory hierarchy.
