### ISSUE TITLE
Improve internal links (=header anchors) handling

### ISSUE THREAD

**Issue by jloeser** [hunyadi/md2conf#9]
Currently, only external links are supported. However, there might be documents using header anchors for internal reference.

Example:
```
$ cat internal-link.md
<!-- confluence-page-id: 367198209 -->

Foo

# Test1

Bar

# Test2

See [link](#test1)

See [link](internal-link.md#test2)
```
Both links are valid (GitLab flavored) Markdown according to https://docs.gitlab.com/ee/user/markdown.html#links

Actual behavior is `DocumentError`:
```
2023-08-16 12:15:33,798 - DEBUG - _transform_link [180] - found link #test1 relative to /home/user/internal-link.md
Traceback (most recent call last):
...
md2conf.converter.DocumentError: relative URL points to outside base path: #test1
```

Would be nice to either convert them them accordingly in Confluence (no idea if this is feasible) or to somehow ignore them/change representation. In any case, a valid document should be created.

**Comment by hunyadi** [comment]
I have two main questions:

* How do you assign a unique ID to a Markdown heading or how do you have a unique ID auto-generated from the heading text in order to later use that ID in an anchor?
* How does Confluence assign IDs to Confluence headings?

Some concerns are character case, spaces, special characters, international characters, etc. We would need a robust mapping that can tackle all possible cases. If such an unambiguous mapping were defined, this feature would likely be relatively straightforward to implement.

**Comment by jloeser** [comment]
What do you mean by "how"? From what I see it adds to all headings (h1 to h6) an ID attribute which is basically the heading string with all whitespaces replaced by hypen '-'.

Examples:
```
<h1 id="Welcome-with-Space" data-renderer-start-pos="18">Welcome with Space</h1>
<h1 id="Heading-with-Dash" data-renderer-start-pos="40">Heading-with-Dash</h1>
<h1 id="欢迎来到该网站" data-renderer-start-pos="59">欢迎来到该网站</h1>
<h6 id="myH6" data-renderer-start-pos="98">myH6</h6>
<h1 id="Vítejte-na-stránkách" data-renderer-start-pos="106">Vítejte na stránkách</h1>
```
Resulting HTML looks quite straight forward:
```
<a data-testid="link-with-safety" href="#Vítejte-na-stránkách" title="#Vítejte-na-stránkách" data-renderer-mark="true" class="css-tgpl01">Vítejte na stránkách</a>
```


> Some concerns are character case, spaces, special characters, international characters, etc.

Yes, I had them two however it looks like this is quite robust (I tested with some translated Czech and Chinese Strings).

**Comment by jloeser** [comment]
Well, the second case didn't work for me:

```
$ tail -n +3 internal-link.md

Foo

# Test1

Bar

# Test2

See [link](#Test1)

See [link](internal-link.md#Test2)
```
```
$ python3 -m md2conf /home/jloeser/devel/git/atix/janloe/notes/confluence/internal-link.md -l debug
2023-08-22 17:09:21,198 - INFO - _synchronize_page [87] - Synchronizing page: /home/jloeser/devel/git/atix/janloe/notes/confluence/internal-link.md
2023-08-22 17:09:21,204 - DEBUG - build_extension [153] - Successfully imported extension module "markdown.extensions.tables".
2023-08-22 17:09:21,204 - DEBUG - registerExtensions [116] - Successfully loaded extension "markdown.extensions.tables.TableExtension".
2023-08-22 17:09:21,207 - DEBUG - build_extension [153] - Successfully imported extension module "markdown.extensions.fenced_code".
2023-08-22 17:09:21,207 - DEBUG - registerExtensions [116] - Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
2023-08-22 17:09:21,209 - DEBUG - build_extension [153] - Successfully imported extension module "pymdownx.tilde".
2023-08-22 17:09:21,210 - DEBUG - registerExtensions [116] - Successfully loaded extension "pymdownx.tilde.DeleteSubExtension".
2023-08-22 17:09:21,210 - DEBUG - registerExtensions [116] - Successfully loaded extension "markdown.extensions.sane_lists.SaneListExtension".
2023-08-22 17:09:21,212 - DEBUG - _transform_link [180] - found link #Test1 relative to /home/jloeser/devel/git/atix/janloe/notes/confluence/internal-link.md
2023-08-22 17:09:21,212 - DEBUG - _transform_link [190] - found local URL: #Test1
2023-08-22 17:09:21,212 - DEBUG - _transform_link [180] - found link internal-link.md#Test2 relative to /home/jloeser/devel/git/atix/janloe/notes/confluence/internal-link.md
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jloeser/devel/envs/md2conf-env/lib/python3.10/site-packages/md2conf/__main__.py", line 85, in <module>
    Application(api, ConfluenceDocumentOptions(args.generated_by)).synchronize(
  File "/home/jloeser/devel/envs/md2conf-env/lib/python3.10/site-packages/md2conf/application.py", line 34, in synchronize
    self.synchronize_page(path)
  File "/home/jloeser/devel/envs/md2conf-env/lib/python3.10/site-packages/md2conf/application.py", line 41, in synchronize_page
    self._synchronize_page(page_path, dict())
  File "/home/jloeser/devel/envs/md2conf-env/lib/python3.10/site-packages/md2conf/application.py", line 88, in _synchronize_page
    document = ConfluenceDocument(page_path, self.options, page_metadata)
  File "/home/jloeser/devel/envs/md2conf-env/lib/python3.10/site-packages/md2conf/converter.py", line 418, in __init__
    converter.visit(self.root)
  File "/home/jloeser/devel/envs/md2conf-env/lib/python3.10/site-packages/md2conf/converter.py", line 143, in visit
    self.visit(source)
  File "/home/jloeser/devel/envs/md2conf-env/lib/python3.10/site-packages/md2conf/converter.py", line 139, in visit
    target = self.transform(source)
  File "/home/jloeser/devel/envs/md2conf-env/lib/python3.10/site-packages/md2conf/converter.py", line 307, in transform
    return self._transform_link(child)
  File "/home/jloeser/devel/envs/md2conf-env/lib/python3.10/site-packages/md2conf/converter.py", line 205, in _transform_link
    raise DocumentError(f"unable to find matching page for URL: {url}")
md2conf.converter.DocumentError: unable to find matching page for URL: internal-link.md#Test2
```

Any ideas on the fly?

**Comment by hunyadi** [comment]
You can only reference documents in relative links if you are synchronizing a directory tree. This is because the Markdown to Confluence converter only scans the file system and maintains a catalog of valid file names if it is processing a set of documents but not when it is processing a single document. However, you would typically use the short-hand notation `#heading-1` to reference a heading in the same document, and not the redundant notation that includes the file name. Specifically, the more redundant syntax is not robust against renaming the file.

**Comment by jloeser** [comment]
Thanks for explanation, I can live with the short-had notation for referencing inside same document.

> Specifically, the more redundant syntax is not robust against renaming the file.

True.
